name: 'dbt_pilotage'
version: '1.0.0'
config-version: 2

profile: 'dbt_pilotage'

model-paths: ["dbt/models"]
analysis-paths: ["dbt/analyses"]
test-paths: ["dbt/tests"]
seed-paths: ["dbt/seeds"]
macro-paths: ["dbt/macros"]
snapshot-paths: ["dbt/snapshots"]

packages-install-path: "dbt/packages"

models:
  dbt_pilotage:
    legacy:
      +materialized: table
      appartenance_geo_communes:
        +column_types:
          code_insee: varchar(5)


seeds:
  dbt_pilotage:
    sa_ept:
      +column_types:
        departement: varchar(3)
        code_comm: varchar(25)
