services:
  minio:
    image: bitnami/minio
    container_name: pilotage_minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "127.0.0.1:${MINIO_PORT_ON_DOCKER_HOST:-9000}:9000"
      - "127.0.0.1:${MINIO_ADMIN_PORT_ON_DOCKER_HOST:-9001}:9001"
    volumes:
      - minio_data:/bitnami/minio/data

  postgres:
    container_name: pilotage_postgres
    image: postgres:17
    # Disable some safety switches for a faster postgres: https://www.postgresql.org/docs/current/non-durability.html
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      # Required by the "_/postgres" image
      - POSTGRES_PASSWORD=password
      # Avoid a log error when starting the container:
      # > Role "root" does not exist.
      # Without this variable, the default Unix account ('root')
      # is used automatically when starting postgres.
      # https://www.postgresql.org/docs/current/libpq-envars.html
      - PGUSER=postgres
      - PGPASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT_ON_DOCKER_HOST:-5432}:5432"

  airflow:
    container_name: pilotage_airflow
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://postgres:password@postgres:5432/airflow
      - AIRFLOW_CONN_LOG_CONNECTION=aws:///?__extra__=%7B%22endpoint_url%22%3A+%22http%3A%2F%2Fminio:9000%22%2C+%22aws_access_key_id%22%3A+%22minioadmin%22%2C+%22aws_secret_access_key%22%3A+%22minioadmin%22%2C+%22config_kwargs%22%3A+%7B%22request_checksum_calculation%22%3A+%22when_required%22%2C+%22response_checksum_validation%22%3A+%22when_required%22%7D%7D
      - AIRFLOW_CONN_S3_DOCS=aws:///?__extra__=%7B%22endpoint_url%22%3A+%22http%3A%2F%2Fminio:9000%22%2C+%22aws_access_key_id%22%3A+%22minioadmin%22%2C+%22aws_secret_access_key%22%3A+%22minioadmin%22%2C+%22config_kwargs%22%3A+%7B%22request_checksum_calculation%22%3A+%22when_required%22%2C+%22response_checksum_validation%22%3A+%22when_required%22%7D%7D
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://airflow/logs
      - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=log_connection
      - AIRFLOW__LOGGING__ENCRYPT_S3_LOGS=False
    depends_on:
      - postgres
      - minio
    build:
      context: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:${AIRFLOW_PORT_ON_DOCKER_HOST:-8080}:8080"
    volumes:
      - ./custom-dev-entrypoint.sh:/entrypoint.sh
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt

volumes:
  postgres_data:
  minio_data:
