dbt_pilotage:
  outputs:
    main_fal:
      type: fal
      db_profile: main

    main:
      schema: public
      threads: 4
      type: postgres
      dbname: "{{ env_var('PGDATABASE') }}"
      host: "{{ env_var('PGHOST') }}"
      password: "{{ env_var('PGPASSWORD', '') }}"
      port: "{{ env_var('PGPORT') | int }}"
      user: "{{ env_var('PGUSER') }}"

  target: main_fal
