select
    contacts."EMAIL",
    contacts."STRUCTURE",
    contacts."Réseau",
    contacts."LIEN_TALLY",
    contacts."Date jour",
    contacts."Date de dernière commande",
    contacts."Tel",
    contacts."Fonction",
    contacts."Contact",
    contacts."LIEN_BARO",
    contacts."Code postal",
    contacts."Nombre d'envois du baromètre",
    contacts."Type de Structure",
    contacts."Date de première commande",
    contacts."Date envoi mail Relance J+71",
    contacts."Fonction (recatégorisée)",
    contacts."Structure-réseau-label",
    contacts."Code dpt",
    contacts."Objectifs de réponses enquêtes",
    contacts."Qui ?",
    contacts."date de l'échange",
    contacts."Vague d'envoi mail enquête usagers",
    contacts."A relancer",
    contacts."Envoyeur",
    contacts."Nbre de réponses à l'enquête au 25/04",
    contacts."Date de dernière réponse au baromètre",
    contacts."Utilise le carnet ?",
    contacts."Date envoi mail merci",
    contacts."Réticences",
    contacts."Estimation par la structure",
    contacts."Infos complémentaires",
    contacts."Suivi appels",
    contacts."Mail CC",
    contacts."Type de contact",
    contacts."Organisation",
    null                                                  as "Commandeur référent",
    null                                                  as "Commandes",
    null::DATE                                            as "date de la dernière commande",
    null                                                  as "Adresse",
    null                                                  as "Ville",
    cmd."declaratif autonomie",
    cmd."declaratif autre outil",
    cmd."declaratif plusieurs freins",
    cmd."declaratif quels freins",
    cmd."Votre structure appartient à une structure, un réseau ou un l",
    dpt.nom_departement,
    dpt.region,
    contacts."Commande passée",
    contacts."Nombre de carnets commandés Total",
    contacts."Nombre de commandes total",
    contacts."Relance baro 30j J+71",
    contacts."Total commandes TTC",
    contacts."Date de dernière commande auto",
    contacts."Kit appropriation envoyé",
    contacts."Manuel",
    contacts."type pour baromètre",
    contacts."Nombre de réponses au baromètre",
    contacts."Envoi mail merci",
    contacts."Logement ?",
    contacts."Conseil Consultatif",
    contacts."Offre découverte",
    contacts."Offre payante (devis validé)",
    (contacts."Date d'envoi du dernier baromètre")::DATE  as "Date d'envoi du dernier baromètre",
    (contacts."Date d'envoi du premier Baromètre")::DATE  as "Date d'envoi du premier Baromètre",
    json_array_element_text(contacts."Source", 0)         as "Source",
    json_array_element_text(contacts."recup fonction", 0) as "recup fonction",
    json_array_element_text(contacts."Secteur", 0)        as "Secteur"
from {{ source('mon_recap', 'Contacts_v0') }} as contacts
left join {{ ref('stg_departement_derniere_commandes') }} as dpt
    on contacts."EMAIL" = dpt.email_commande
left join {{ ref('stg_commandes_max') }} as cmd
    on contacts."EMAIL" = cmd."Email"
