select
    source,
    structure_id,
    id,
    nom,
    description,
    lien_source,
    date_maj,
    type,
    thematiques,
    frais,
    frais_precisions,
    publics,
    publics_precisions,
    conditions_acces,
    commune,
    code_postal,
    code_insee,
    adresse,
    complement_adresse,
    longitude,
    latitude,
    telephone,
    courriel,
    modes_accueil,
    zone_eligibilite,
    contact_nom_prenom,
    lien_mobilisation,
    modes_mobilisation,
    mobilisable_par,
    mobilisation_precisions,
    volume_horaire_hebdomadaire,
    nombre_semaines,
    horaires_accueil,
    adresse_certifiee,
    score_qualite,
    service_thematique,
    service_public,
    service_mode_accueil,
    nom_region,
    code_region_insee,
    nom_departement,
    code_departement_insee
from {{ ref('di_services') }}
left join lateral unnest(thematiques) as service_thematique on true
left join lateral unnest(publics) as service_public on true
left join lateral unnest(modes_accueil) as service_mode_accueil on true
where source != 'soliguide'
