dbt_pilotage:
  outputs:

    main:
      schema: public
      threads: 4
      type: postgres
      dbname: "{{ env_var('PGDATABASE') }}"
      host: "{{ env_var('PGHOST') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      port: "{{ env_var('PGPORT') | int }}"
      user: "{{ env_var('PGUSER') }}"

  target: main
