with services as (
    select *
    from {{ ref('stg_dora__service') }}
),

structures as (
    select *
    from {{ ref('dim_dora__structures') }}
),

final as (
    select
        services.id,
        services.name,
        services.short_desc,
        services.description,
        services.is_cumulative,
        services.fee_details,
        services.beneficiaries_access_modes_other,
        services.coach_orientation_modes_other,
        services.forms,
        services.remote_url,
        services.address1,
        services.address2,
        services.postal_code,
        services.city_code,
        services.city,
        services.recurrence,
        services.suspension_date,
        services.creation_date,
        services.modification_date,
        services.creator_id,
        services.last_editor_id,
        services.structure_id,
        services.slug,
        services.online_form,
        services.publication_date,
        services.diffusion_zone_details,
        services.diffusion_zone_type,
        services.qpv_or_zrr,
        services.is_model,
        services.model_id,
        services.last_sync_checksum,
        services.sync_checksum,
        services.status,
        services.moderation_date,
        services.moderation_status,
        services.fee_condition_id,
        services.data_inclusion_id,
        services.source_id,
        services.data_inclusion_source,
        services.appointment_link,
        services.coach_orientation_modes_external_form_link,
        services.coach_orientation_modes_external_form_link_text,
        services.beneficiaries_access_modes_external_form_link,
        services.beneficiaries_access_modes_external_form_link_text,
        services.duration_weekly_hours,
        services.duration_weeks,
        services.update_frequency,
        services.publics,
        services.publics_precisions,
        services.kind,
        services.service_id_jointure_di,
        services.latitude,
        services.longitude,
        services.update_needed,
        services.dora_url,
        structures.name                  as structure_name,
        structures.siret                 as structure_siret,
        structures.short_desc            as structure_short_desc,
        structures.full_desc             as structure_full_desc,
        structures.url                   as structure_url,
        structures.phone                 as structure_phone,
        structures.email                 as structure_email,
        structures.address1              as structure_address1,
        structures.address2              as structure_address2,
        structures.postal_code           as structure_postal_code,
        structures.city_code             as structure_city_code,
        structures.city                  as structure_city,
        structures.latitude              as structure_latitude,
        structures.longitude             as structure_longitude,
        structures.slug                  as structure_slug,
        structures.department            as structure_department,
        structures.parent_id             as structure_parent_id,
        structures.typology              as structure_typology,
        structures.data_inclusion_id     as structure_data_inclusion_id,
        structures.data_inclusion_source as structure_data_inclusion_source,
        structures.dora_url              as structure_dora_url
    from services
    left join structures
        on services.structure_id = structures.id
)

select * from final
