select
    baro.submission_id                  as "Submission ID",
    baro.respondentid                   as "Respondent ID",
    baro.datesubmission                 as "Submitted at",
    baro.email,
    baro.cost,
    baro.notebooksnumber                as nb_carnets,
    baro.actiontype                     as "type", -- noqa: RF06
    baro.emailbis                       as "Votre adresse mail ?",
    baro.monrecapuse                    as "Votre utilisation de Mon Récap",
    baro.notebooknotused                as "Pouvez-vous expliquer pourquoi vous ne l'avez pas utilisé ?",
    baro.dateorder                      as "Quand avez-vous passé votre commande ?",
    baro.reordercancelled               as "Pourquoi ne l'avez vous pas recommandé ?",
    baro.notebooksnumberbeginning       as "Combien de carnets avez-vous distribués depuis le début de vo",
    baro.notebookreturn                 as "Les usagers reviennent-ils avec le carnet ?",
    baro.notebookreturnalways           as "Les usagers reviennent-ils avec le carnet ? (Toujours)",
    baro.notebookreturnoften            as "Les usagers reviennent-ils avec le carnet ? (Souvent )",
    baro.notebookreturnsometimes        as "Les usagers reviennent-ils avec le carnet ? (Régulièrement)",
    baro.notebookreturnrarely           as "Les usagers reviennent-ils avec le carnet ? (Rarement)",
    baro.notebookreturnnever            as "Les usagers reviennent-ils avec le carnet ? (Jamais)",
    baro.notebookusedwithotherpro       as "Les usagers utilisent-ils, en général, le carnet avec d'autre",
    baro.notebooknotusedwithotherprobis as "Pourquoi les usagers ne l'utilisent pas avec d'autres professio",
    baro.approachimprovement            as "Avez-vous constaté une amélioration dans le parcours de vos u",
    baro.fluidityimprovement            as "D'après vous, la qualité (fluidité, facilité de communicati",
    baro.approvalstatement              as "Dans quelle mesure êtes-vous d'accord avec l'affirmation suiva",
    baro.notebookconstraintreduction    as "Lorsqu'un usager utilise Mon Récap, constatez-vous une meilleu",
    baro.notebookinfluence              as "Diriez-vous que grâce au carnet, les usagers accèdent plus fa",
    baro.timesaved                      as "Temps gagné sur une heure",
    baro.timesavednone                  as "Temps gagné sur une heure (Je ne gagne pas de temps)",
    baro.timesavedlessfivemin           as "Temps gagné sur une heure (Moins de 5min)",
    baro.timesavedfivetenmin            as "Temps gagné sur une heure (Entre 5 et 10min)",
    baro.timesavetenfifteennmin         as "Temps gagné sur une heure (Entre 10 et 15min)",
    baro.timesavefifteenthirtymin       as "Temps gagné sur une heure (Entre 15 et 30min)",
    baro.timesavemorethirtymin          as "Temps gagné sur une heure (Plus de 30min)",
    baro.publictype                     as "Quel(s) type(s) de public accompagnez-vous ?",
    baro.publichandi                    as "Quel(s) type(s) de public accompagnez-vous ? (Personnes en situ",
    baro.publicunemployed               as "Quel(s) type(s) de public accompagnez-vous ? (Personnes éloign",
    baro.publicrsa                      as "Quel(s) type(s) de public accompagnez-vous ? (Bénéficiaires d",
    baro.publicasylumseeker             as "Quel(s) type(s) de public accompagnez-vous ? (Demandeurs d'asil",
    baro.publicjustice                  as "Quel(s) type(s) de public accompagnez-vous ? (Personnes sous ma",
    baro.publicsenior                   as "Quel(s) type(s) de public accompagnez-vous ? (Seniors)",
    baro.publicyoung                    as "Quel(s) type(s) de public accompagnez-vous ? (18 - 25 ans)",
    baro.publichomeless                 as "Quel(s) type(s) de public accompagnez-vous ? (Personnes sans do",
    baro.publicdigitalilliteracy        as "Quel(s) type(s) de public accompagnez-vous ? (illectronisme)",
    baro.publicilliteracy               as "Quel(s) type(s) de public accompagnez-vous ? (illetrisme)",
    baro.publicothers                   as "Quel(s) type(s) de public accompagnez-vous ? (Autres)",
    baro.publicprecision                as "Pouvez-vous préciser ?",
    baro.nps                            as "Quelles sont les chances que vous recommandiez Mon Récap à vo",
    baro.ratiopriceimpact               as "Que pensez-vous de l'équilibre prix / impact du produit ?",
    baro.ratiodetails                   as "Pourquoi ? Pouvez-vous détailler ?",
    baro.suggestion                     as "Un commentaire, une suggestion, une belle histoire ? N'hésitez",
    baro.testimony                      as "Souhaitez-vous témoigner lors d'un prochain webinaire organis",
    baro.usersaction                    as "D'après vous,  [vos usagers expliquent bien les actions ou dé",
    baro.usersorganisation              as "D'après vous,  [vos usagers s'organisent bien]",
    baro.usersdiscussion                as "D'après vous,  [vos usagers ont de l'assurance lors des échan",
    baro.userunderstanding              as "D'après vous,  [vous comprenez facilement le besoin d'aide]",
    baro.userhelp                       as "D'après vous,  [vous résolvez rapidement les demandes d'aide]",
    baro.usertrust                      as "D'après vous,  [vous créez facilement un lien de confiance av",
    baro.trajectoryexample              as "Si vous en avez un en tête, racontez-nous un exemple de parcou",
    baro.notebookmanyusers              as "Avez-vous distribué plusieurs carnets à certains usagers ?",
    baro.notebookamountmanyusers        as "Si oui, combien de vos usagers ont reçu plusieurs carnets ?",
    baro.useramounthelper               as "D'après vous, vos usagers peuvent rencontrer combien d'accompa",
    baro.notebooksales                  as "D'après vous, votre structure serait-elle prête à payer pour",
    baro.notebookprice                  as "Si oui, combien par carnet ?",
    baro.useramountnotebookreceived     as "Combien d'usagers ont reçu au moins un carnet (approximativeme",
    baro.usernotebooklost               as "Parmi ces usagers, combien d'usagers ont perdu le carnet ou ne",
    baro.monrecapactions                as "D'après vous, Mon Récap permet aux usagers de ?  [mieux expli",
    baro.monrecaporganisation           as "D'après vous, Mon Récap permet aux usagers de ?  [mieux s'org",
    baro.monrecapdiscussion             as "D'après vous, Mon Récap permet aux usagers de ?  [avoir plus",
    baro.monrecapuserother              as "D'après vous, Mon Récap permet aux usagers de ?  [résoudre p",
    baro.monrecapproblemsolver          as "D'après vous, Mon Récap permet aux usagers de ?  [Autre (à d",
    baro.monrecapunderstanding          as "D'après vous, Mon Récap vous permet de ? [avoir une meilleure",
    baro.monrecaprelationship           as "D'après vous, Mon Récap vous permet de ? [découvrir que l'us",
    baro.monrecaphelpseeking            as "D'après vous, Mon Récap vous permet de ? [Créer plus facilem",
    baro.monrecapother                  as "D'après vous, Mon Récap vous permet de ? [Autre (à détaille",
    baro.monrecapdetailledhelp          as "Pouvez-vous détailler ? D'après vous, Mon Récap permet aussi",
    baro.monrecapdetailleduserhelp      as "Pouvez-vous détailler ? D'après vous, Mon Récap vous permet",
    baro.notebookdigital                as "Souhaiteriez-vous une version numérique (en plus de la version",
    baro.notebookwriting                as "Les personnes écrivent-elles seules dans leur carnet ?",
    baro.notebookrefusal                as "Avez-vous des refus d'utilisation de la part des usagers",
    baro.notebookrefusalreason          as "Pouvez-vous expliquer les raisons du refus d'utilisation ?",
    baro.notebookdigitalapproval        as "Pourquoi pensez-vous qu'avoir une version numérique serait une",
    baro.notebookdigitalreplacement     as "Seriez-vous prêt à remplacer la version numérique par la ver",
    dpt.nom_departement,
    dpt.region
from {{ source('monrecap', 'raw_barometre') }} as baro
left join {{ ref('stg_departement_derniere_commandes') }} as dpt
    on dpt.email_commande = coalesce(baro.email, baro.emailbis)
