select
    id,
    campaign_year,
    state,
    label_geiq_id,
    conventionned_institutions_departments,
    with_main_geiq,
    antenna_nb,
    employee_nb,
    convention_amount,
    granted_amount,
    advance_amount,
    created_at,
    contracts_selection_validated_at,
    submitted_at,
    grants_selection_validated_at,
    decision_validated_at,
    reviewed_at,
    final_reviewed_at,
    reviewed_by_institution_id,
    final_reviewed_by_institution_id,
    date_mise_à_jour_metabase,
    final_reviewed_at is not null as is_final_reviewed
from {{ ref('stg_geiq__assessments') }}
