select
    c_territoire_id                               as id_clpe,
    c_lblterritoire                               as libelle_clpe,
    dptres                                        as departement,
    regres                                        as region,
    categorie_statistique                         as categorie_demandeurs_emploi,
    tranche_anciennete                            as anciennete_demandeurs_emploi,
    top_qpv                                       as resident_qpv,
    top_zrr                                       as resident_zrr,
    top_boe                                       as beneficiaire_obligation_emploi,
    top_rsa                                       as beneficiaire_rsa,
    tranche_age,
    niveau_de_formation,
    sexe,
    situation_de_famille,
    nombre_enfants_a_charge,
    structure_accompagnement,
    parcours_accompagnement,
    defm                                          as nombre_demandeurs_emploi,
    contrainte_numerique                          as frein_numerique,
    c_impactcontrainte_numeriq_id                 as intensite_frein_numerique,
    contrainte_mobilite                           as frein_mobilite,
    c_impactcontrainte_mobilite_id                as intensite_frein_mobilite,
    contrainte_familiale                          as frein_familial,
    c_impactcontrainte_famille_id                 as intensite_frein_familiale,
    contrainte_sante                              as frein_sante,
    c_impactcontrainte_sante_id                   as intensite_frein_sante,
    contrainte_savoir                             as frein_savoir,
    c_impactcontrainte_savoir_id                  as intensite_frein_savoir,
    contrainte_logement                           as frein_logement,
    c_impactcontrainte_logement_id                as intensite_frein_logement,
    contrainte_financiere                         as frein_financier,
    c_impactcontrainte_finance_id                 as intensite_frein_financiere,
    contrainte_admin_jurid                        as frein_admin_jur,
    c_impactcontrainte_adminjur_id                as intensite_frein_admin_jur,
    n_nbcontraintesactives,
    diag                                          as nombre_de_diagnostics,
    case
        when diag is null then 'NON'
        else 'OUI'
    end                                           as diagnostic_effectue,
    to_date(mois_statistique || '01', 'YYYYMMDD') as date_extraction
from {{ source("france_travail","data_diag_ft") }}
