select
    domaine_professionnel,
    grand_domaine,
    rome,
    "métier",
    "nom_département_structure",
    "département_structure",
    "région_structure",
    epci_structure,
    bassin_emploi_structure,
    type_structure,
    categorie_structure,
    id_structure,
    nom_structure,
    etape,
    sum(valeur) as valeur
from {{ ref('fdp_tension') }}
group by
    domaine_professionnel,
    grand_domaine,
    rome,
    "métier",
    "nom_département_structure",
    "département_structure",
    "région_structure",
    epci_structure,
    bassin_emploi_structure,
    type_structure,
    categorie_structure,
    id_structure,
    nom_structure,
    etape
