with source as (

    select *
    from {{ source('raw', 'fagerh_reponses') }}

),

renamed as (

    select

        {{ clean_text('uuid') }} as uuid,
        {{ clean_text('id') }} as id,
        {{ clean_boolean('ESRP activé') }} as esrp_active,
        {{ clean_numeric('ETP ESRP') }} as esrp_etp,
        {{ clean_boolean('ESPO activé') }} as espo_active,
        {{ clean_numeric('ETP ESPO') }} as espo_etp,
        {{ clean_boolean('UEROS activé') }} as ueros_active,
        {{ clean_numeric('ETP UEROS') }} as ueros_etp,
        {{ clean_boolean('DEAc activé') }} as deac_active,
        {{ clean_numeric('ETP DEAc') }} as deac_etp,
        {{ clean_boolean('PEC') }} as pec,
        {{ clean_text('Métiers (JSON)') }} as metiers_json,
        {{ clean_text('Q32 Implantation') }} as q32_implantation,
        {{ clean_boolean('Q33 Transports') }} as q33_transports,
        {{ clean_boolean('Q33 PMR') }} as q33_pmr,
        {{ clean_boolean('Q33 Alternatif') }} as q33_alternatif,
        {{ clean_text('Q34 Préfecture') }} as q34_prefecture,
        {{ clean_boolean('Q35 Hébergement') }} as q35_hebergement,
        {{ clean_integer('Q35 Places') }} as q35_places,
        {{ clean_boolean('Q35 Weekend') }} as q35_weekend,
        {{ clean_text('Q35 Comptabilité') }} as q35_comptabilite,
        {{ clean_boolean('Q36 Restaurant') }} as q36_restaurant,
        {{ clean_boolean('Q37 Cuisine') }} as q37_cuisine,
        {{ clean_text('Q38 Externe') }} as q38_externe,
        {{ clean_text('Q38 Participation') }} as q38_participation,
        {{ clean_text('Q39 Weekend') }} as q39_weekend,
        {{ clean_boolean('Q40 Rémunération') }} as q40_remuneration,
        {{ clean_text('Q40 Opérateur') }} as q40_operateur,
        {{ clean_integer('Q41 ESAT') }} as q41_esat,
        {{ clean_integer('Q42 EA') }} as q42_ea,
        {{ clean_integer('Q43 EI') }} as q43_ei,
        {{ clean_text('Q44 CCAS') }} as q44_ccas,
        {{ clean_text('Q45 CPTS') }} as q45_cpts,
        {{ clean_text('Q46 CPT') }} as q46_cpt,
        {{ clean_text('Q46 Fagerh') }} as q46_fagerh,
        {{ clean_text('Q47 CLSM') }} as q47_clsm,
        {{ clean_text('Q47 Fagerh') }} as q47_fagerh,
        {{ clean_text('Q48 CLE') }} as q48_cle,
        {{ clean_text('Q48 Fagerh') }} as q48_fagerh,
        {{ clean_text('Q49 CRE') }} as q49_cre,
        {{ clean_text('Q49 Fagerh') }} as q49_fagerh,
        {{ clean_text('Q50 FIPHFP') }} as q50_fiphfp,
        {{ clean_text('Q50 Fagerh') }} as q50_fagerh,
        {{ clean_text('Q51 PLITH') }} as q51_plith,
        {{ clean_text('Q51 Fagerh') }} as q51_fagerh,
        {{ clean_text('Q52 AFPA') }} as q52_afpa,
        {{ clean_integer('Q53 Accompagnés') }} as q53_personnes_accompagnees,
        {{ clean_integer('Q54 Sorties') }} as q54_sorties,
        {{ clean_integer('Q55 Journées ESRP') }} as q55_journees_esrp,
        {{ clean_integer('Q56 Journées ESPO') }} as q56_journees_espo,
        {{ clean_integer('Q57 Journées UEROS') }} as q57_journees_ueros,
        {{ clean_integer('Genre Hommes') }} as genre_hommes,
        {{ clean_integer('Genre Femmes') }} as genre_femmes,
        {{ clean_integer('Genre Non-binaires') }} as genre_non_binaires,
        {{ clean_integer('Age 16-17') }} as age_16_17,
        {{ clean_integer('Age 18-19') }} as age_18_19,
        {{ clean_integer('Age 20-24') }} as age_20_24,
        {{ clean_integer('Age 25-29') }} as age_25_29,
        {{ clean_integer('Age 30-34') }} as age_30_34,
        {{ clean_integer('Age 35-39') }} as age_35_39,
        {{ clean_integer('Age 40-44') }} as age_40_44,
        {{ clean_integer('Age 45-49') }} as age_45_49,
        {{ clean_integer('Age 50-54') }} as age_50_54,
        {{ clean_integer('Age 60+') }} as age_60_plus,
        {{ clean_integer('Formation Niveau 2') }} as formation_niveau_2,
        {{ clean_integer('Formation Niveau 3') }} as formation_niveau_3,
        {{ clean_integer('Formation Niveau 4') }} as formation_niveau_4,
        {{ clean_integer('Formation Niveau 5') }} as formation_niveau_5,
        {{ clean_integer('Formation Niveau 6') }} as formation_niveau_6,
        {{ clean_integer('Formation Niveau 7') }} as formation_niveau_7,
        {{ clean_integer('1 pathologie') }} as une_pathologie,
        {{ clean_integer('2 pathologies') }} as deux_pathologies,
        {{ clean_integer('3+ pathologies') }} as trois_pathologies_ou_plus,
        {{ clean_integer('Pathologies inconnu') }} as pathologies_inconnu,
        {{ clean_integer('Déf. intellectuelles (P)') }} as def_intellectuelles_p,
        {{ clean_integer('Déf. intellectuelles (A)') }} as def_intellectuelles_a,
        {{ clean_integer('Autisme (P)') }} as autisme_p,
        {{ clean_integer('Autisme (A)') }} as autisme_a,
        {{ clean_integer('Troubles psychiques (P)') }} as troubles_psychiques_p,
        {{ clean_integer('Troubles psychiques (A)') }} as troubles_psychiques_a,
        {{ clean_integer('Troubles langage (P)') }} as troubles_langage_p,
        {{ clean_integer('Troubles langage (A)') }} as troubles_langage_a,
        {{ clean_integer('Déf. auditives (P)') }} as def_auditives_p,
        {{ clean_integer('Déf. auditives (A)') }} as def_auditives_a,
        {{ clean_integer('Déf. visuelles (P)') }} as def_visuelles_p,
        {{ clean_integer('Déf. visuelles (A)') }} as def_visuelles_a,
        {{ clean_integer('Déf. motrices (P)') }} as def_motrices_p,
        {{ clean_integer('Déf. motrices (A)') }} as def_motrices_a,
        {{ clean_integer('Déf. métaboliques (P)') }} as def_metaboliques_p,
        {{ clean_integer('Déf. métaboliques (A)') }} as def_metaboliques_a,
        {{ clean_integer('Cérébro-lésions (P)') }} as cerebro_lesions_p,
        {{ clean_integer('Cérébro-lésions (A)') }} as cerebro_lesions_a,
        {{ clean_integer('Polyhandicap (P)') }} as polyhandicap_p,
        {{ clean_integer('Polyhandicap (A)') }} as polyhandicap_a,
        {{ clean_integer('TCC (P)') }} as tcc_p,
        {{ clean_integer('TCC (A)') }} as tcc_a,
        {{ clean_integer('Diagnostics en cours (P)') }} as diagnostics_en_cours_p,
        {{ clean_integer('Diagnostics en cours (A)') }} as diagnostics_en_cours_a,
        {{ clean_integer('Autres déf. (P)') }} as autres_def_p,
        {{ clean_integer('Autres déf. (A)') }} as autres_def_a,
        {{ clean_integer('Origine congénitale') }} as origine_congenitale,
        {{ clean_integer('Origine maladie') }} as origine_maladie,
        {{ clean_integer('Origine accident vie') }} as origine_accident_vie,
        {{ clean_integer('Origine accident travail') }} as origine_accident_travail,
        {{ clean_integer('Origine maladie pro') }} as origine_maladie_pro,
        {{ clean_integer('Origine autres') }} as origine_autres,
        {{ clean_integer('Origine inconnue') }} as origine_inconnue,
        {{ clean_integer('Lésion traumatisme') }} as lesion_traumatisme,
        {{ clean_integer('Lésion AVC') }} as lesion_avc,
        {{ clean_integer('Lésion tumeur') }} as lesion_tumeur,
        {{ clean_integer('Lésion épilepsie') }} as lesion_epilepsie,
        {{ clean_integer('Lésion autres') }} as lesion_autres,
        {{ clean_integer('Lésion inconnue') }} as lesion_inconnue,
        {{ clean_integer('Entrée emploi privé') }} as entree_emploi_prive,
        {{ clean_integer('Entrée EA') }} as entree_ea,
        {{ clean_integer('Entrée privé alternance') }} as entree_prive_alternance,
        {{ clean_integer('Entrée emploi public') }} as entree_emploi_public,
        {{ clean_integer('Entrée FPT') }} as entree_fpt,
        {{ clean_integer('Entrée FPT contractuels') }} as entree_fpt_contractuels,
        {{ clean_integer('Entrée FPT alternance') }} as entree_fpt_alternance,
        {{ clean_integer('Entrée FPH') }} as entree_fph,
        {{ clean_integer('Entrée FPH contractuels') }} as entree_fph_contractuels,
        {{ clean_integer('Entrée FPH alternance') }} as entree_fph_alternance,
        {{ clean_integer('Entrée FPE') }} as entree_fpe,
        {{ clean_integer('Entrée FPE contractuels') }} as entree_fpe_contractuels,
        {{ clean_integer('Entrée FPE alternance') }} as entree_fpe_alternance,
        {{ clean_integer('Entrée non salarié') }} as entree_non_salarie,
        {{ clean_integer('Entrée ESAT') }} as entree_esat,
        {{ clean_integer('Entrée sans emploi') }} as entree_sans_emploi,
        {{ clean_integer('Sans emploi <1an') }} as sans_emploi_moins_1_an,
        {{ clean_integer('Sans emploi 1-2ans') }} as sans_emploi_1_2_ans,
        {{ clean_integer('Sans emploi >2ans') }} as sans_emploi_plus_2_ans,
        {{ clean_integer('Jamais travaillé') }} as jamais_travaille,
        {{ clean_integer('En formation') }} as en_formation,
        {{ clean_integer('Ressources rémunération') }} as ressources_remuneration,
        {{ clean_integer('Ressources AAH') }} as ressources_aah,
        {{ clean_integer('Ressources chômage') }} as ressources_chomage,
        {{ clean_integer('Ressources RSA') }} as ressources_rsa,
        {{ clean_integer('Ressources IJ') }} as ressources_ij,
        {{ clean_integer('Ressources rentes') }} as ressources_rentes,
        {{ clean_integer('Ressources autres') }} as ressources_autres,
        {{ clean_integer('Ressources aucune') }} as ressources_aucune,
        {{ clean_integer('Ressources inconnu') }} as ressources_inconnu,
        {{ clean_integer('Heures absence') }} as heures_absence,
        {{ clean_integer('Heures théoriques') }} as heures_theoriques,
        {{ clean_integer('Sorties anticipées') }} as sorties_anticipees,
        {{ clean_integer('Sortie volontaire') }} as sortie_volontaire,
        {{ clean_integer('Sortie santé') }} as sortie_sante,
        {{ clean_integer('Sortie réorientation') }} as sortie_reorientation,
        {{ clean_integer('Sortie disciplinaire') }} as sortie_disciplinaire,
        {{ clean_integer('Sortie objectif atteint') }} as sortie_objectif_atteint,
        {{ clean_integer('Sortie emploi') }} as sortie_emploi,
        {{ clean_integer('Sortie inconnue') }} as sortie_inconnue,
        {{ clean_integer('Sortie autres') }} as sortie_autres,
        {{ clean_integer('Suspensions nb') }} as suspensions_nb,
        {{ clean_integer('Suspension santé') }} as suspension_sante,
        {{ clean_integer('Suspension handicap') }} as suspension_handicap,
        {{ clean_integer('Suspension sociale') }} as suspension_sociale,
        {{ clean_integer('Suspension parcours') }} as suspension_parcours,
        {{ clean_integer('Suspension autres') }} as suspension_autres,
        {{ clean_integer('Suspensions reprises') }} as suspensions_reprises,
        {{ clean_text('Géographie (JSON)') }} as geographie_json,
        {{ clean_text('Prestations (JSON)') }} as prestations_json,
        {{ clean_text('A') }} as a,
        {{ clean_text('abs_heures__deac') }} as abs_heures__deac,
        {{ clean_text('abs_heures__espo') }} as abs_heures__espo,
        {{ clean_text('abs_heures__esrp') }} as abs_heures__esrp,
        {{ clean_text('abs_heures__ueros') }} as abs_heures__ueros,
        {{ clean_text('abs_heures_theoriques__deac') }} as abs_heures_theoriques__deac,
        {{ clean_text('abs_heures_theoriques__espo') }} as abs_heures_theoriques__espo,
        {{ clean_text('abs_heures_theoriques__esrp') }} as abs_heures_theoriques__esrp,
        {{ clean_text('abs_heures_theoriques__ueros') }} as abs_heures_theoriques__ueros,
        {{ clean_integer('age_16_17__deac') }} as age_16_17__deac,
        {{ clean_integer('age_16_17__espo') }} as age_16_17__espo,
        {{ clean_integer('age_16_17__esrp') }} as age_16_17__esrp,
        {{ clean_integer('age_16_17__ueros') }} as age_16_17__ueros,
        {{ clean_integer('age_18_19__deac') }} as age_18_19__deac,
        {{ clean_integer('age_18_19__espo') }} as age_18_19__espo,
        {{ clean_integer('age_18_19__esrp') }} as age_18_19__esrp,
        {{ clean_integer('age_18_19__ueros') }} as age_18_19__ueros,
        {{ clean_integer('age_20_24__deac') }} as age_20_24__deac,
        {{ clean_integer('age_20_24__espo') }} as age_20_24__espo,
        {{ clean_integer('age_20_24__esrp') }} as age_20_24__esrp,
        {{ clean_integer('age_20_24__ueros') }} as age_20_24__ueros,
        {{ clean_integer('age_25_29__deac') }} as age_25_29__deac,
        {{ clean_integer('age_25_29__espo') }} as age_25_29__espo,
        {{ clean_integer('age_25_29__esrp') }} as age_25_29__esrp,
        {{ clean_integer('age_25_29__ueros') }} as age_25_29__ueros,
        {{ clean_integer('age_30_34__deac') }} as age_30_34__deac,
        {{ clean_integer('age_30_34__espo') }} as age_30_34__espo,
        {{ clean_integer('age_30_34__esrp') }} as age_30_34__esrp,
        {{ clean_integer('age_30_34__ueros') }} as age_30_34__ueros,
        {{ clean_integer('age_35_39__deac') }} as age_35_39__deac,
        {{ clean_integer('age_35_39__espo') }} as age_35_39__espo,
        {{ clean_integer('age_35_39__esrp') }} as age_35_39__esrp,
        {{ clean_integer('age_35_39__ueros') }} as age_35_39__ueros,
        {{ clean_integer('age_40_44__deac') }} as age_40_44__deac,
        {{ clean_integer('age_40_44__espo') }} as age_40_44__espo,
        {{ clean_integer('age_40_44__esrp') }} as age_40_44__esrp,
        {{ clean_integer('age_40_44__ueros') }} as age_40_44__ueros,
        {{ clean_integer('age_45_49__deac') }} as age_45_49__deac,
        {{ clean_integer('age_45_49__espo') }} as age_45_49__espo,
        {{ clean_integer('age_45_49__esrp') }} as age_45_49__esrp,
        {{ clean_integer('age_45_49__ueros') }} as age_45_49__ueros,
        {{ clean_integer('age_50_54__deac') }} as age_50_54__deac,
        {{ clean_integer('age_50_54__espo') }} as age_50_54__espo,
        {{ clean_integer('age_50_54__esrp') }} as age_50_54__esrp,
        {{ clean_integer('age_50_54__ueros') }} as age_50_54__ueros,
        {{ clean_integer('age_60_plus__deac') }} as age_60_plus__deac,
        {{ clean_integer('age_60_plus__espo') }} as age_60_plus__espo,
        {{ clean_integer('age_60_plus__esrp') }} as age_60_plus__esrp,
        {{ clean_integer('age_60_plus__ueros') }} as age_60_plus__ueros,
        {{ clean_integer('entree_emploi_prive__deac') }} as entree_emploi_prive__deac,
        {{ clean_integer('entree_emploi_prive__espo') }} as entree_emploi_prive__espo,
        {{ clean_integer('entree_emploi_prive__esrp') }} as entree_emploi_prive__esrp,
        {{ clean_integer('entree_emploi_prive__ueros') }} as entree_emploi_prive__ueros,
        {{ clean_integer('entree_emploi_prive_alternance__deac') }} as entree_emploi_prive_alternance__deac,
        {{ clean_integer('entree_emploi_prive_alternance__espo') }} as entree_emploi_prive_alternance__espo,
        {{ clean_integer('entree_emploi_prive_alternance__esrp') }} as entree_emploi_prive_alternance__esrp,
        {{ clean_integer('entree_emploi_prive_alternance__ueros') }} as entree_emploi_prive_alternance__ueros,
        {{ clean_integer('entree_emploi_prive_ea__deac') }} as entree_emploi_prive_ea__deac,
        {{ clean_integer('entree_emploi_prive_ea__espo') }} as entree_emploi_prive_ea__espo,
        {{ clean_integer('entree_emploi_prive_ea__esrp') }} as entree_emploi_prive_ea__esrp,
        {{ clean_integer('entree_emploi_prive_ea__ueros') }} as entree_emploi_prive_ea__ueros,
        {{ clean_integer('entree_emploi_public__deac') }} as entree_emploi_public__deac,
        {{ clean_integer('entree_emploi_public__espo') }} as entree_emploi_public__espo,
        {{ clean_integer('entree_emploi_public__esrp') }} as entree_emploi_public__esrp,
        {{ clean_integer('entree_emploi_public__ueros') }} as entree_emploi_public__ueros,
        {{ clean_integer('entree_esat__deac') }} as entree_esat__deac,
        {{ clean_integer('entree_esat__espo') }} as entree_esat__espo,
        {{ clean_integer('entree_esat__esrp') }} as entree_esat__esrp,
        {{ clean_integer('entree_esat__ueros') }} as entree_esat__ueros,
        {{ clean_integer('entree_formation__deac') }} as entree_formation__deac,
        {{ clean_integer('entree_formation__espo') }} as entree_formation__espo,
        {{ clean_integer('entree_formation__esrp') }} as entree_formation__esrp,
        {{ clean_integer('entree_formation__ueros') }} as entree_formation__ueros,
        {{ clean_integer('entree_fpe__deac') }} as entree_fpe__deac,
        {{ clean_integer('entree_fpe__espo') }} as entree_fpe__espo,
        {{ clean_integer('entree_fpe__esrp') }} as entree_fpe__esrp,
        {{ clean_integer('entree_fpe__ueros') }} as entree_fpe__ueros,
        {{ clean_integer('entree_fpe_alternance__deac') }} as entree_fpe_alternance__deac,
        {{ clean_integer('entree_fpe_alternance__espo') }} as entree_fpe_alternance__espo,
        {{ clean_integer('entree_fpe_alternance__esrp') }} as entree_fpe_alternance__esrp,
        {{ clean_integer('entree_fpe_alternance__ueros') }} as entree_fpe_alternance__ueros,
        {{ clean_integer('entree_fpe_contractuels__deac') }} as entree_fpe_contractuels__deac,
        {{ clean_integer('entree_fpe_contractuels__espo') }} as entree_fpe_contractuels__espo,
        {{ clean_integer('entree_fpe_contractuels__esrp') }} as entree_fpe_contractuels__esrp,
        {{ clean_integer('entree_fpe_contractuels__ueros') }} as entree_fpe_contractuels__ueros,
        {{ clean_integer('entree_fph__deac') }} as entree_fph__deac,
        {{ clean_integer('entree_fph__espo') }} as entree_fph__espo,
        {{ clean_integer('entree_fph__esrp') }} as entree_fph__esrp,
        {{ clean_integer('entree_fph__ueros') }} as entree_fph__ueros,
        {{ clean_integer('entree_fph_alternance__deac') }} as entree_fph_alternance__deac,
        {{ clean_integer('entree_fph_alternance__espo') }} as entree_fph_alternance__espo,
        {{ clean_integer('entree_fph_alternance__esrp') }} as entree_fph_alternance__esrp,
        {{ clean_integer('entree_fph_alternance__ueros') }} as entree_fph_alternance__ueros,
        {{ clean_integer('entree_fph_contractuels__deac') }} as entree_fph_contractuels__deac,
        {{ clean_integer('entree_fph_contractuels__espo') }} as entree_fph_contractuels__espo,
        {{ clean_integer('entree_fph_contractuels__esrp') }} as entree_fph_contractuels__esrp,
        {{ clean_integer('entree_fph_contractuels__ueros') }} as entree_fph_contractuels__ueros,
        {{ clean_integer('entree_fpt__deac') }} as entree_fpt__deac,
        {{ clean_integer('entree_fpt__espo') }} as entree_fpt__espo,
        {{ clean_integer('entree_fpt__esrp') }} as entree_fpt__esrp,
        {{ clean_integer('entree_fpt__ueros') }} as entree_fpt__ueros,
        {{ clean_integer('entree_fpt_alternance__deac') }} as entree_fpt_alternance__deac,
        {{ clean_integer('entree_fpt_alternance__espo') }} as entree_fpt_alternance__espo,
        {{ clean_integer('entree_fpt_alternance__esrp') }} as entree_fpt_alternance__esrp,
        {{ clean_integer('entree_fpt_alternance__ueros') }} as entree_fpt_alternance__ueros,
        {{ clean_integer('entree_fpt_contractuels__deac') }} as entree_fpt_contractuels__deac,
        {{ clean_integer('entree_fpt_contractuels__espo') }} as entree_fpt_contractuels__espo,
        {{ clean_integer('entree_fpt_contractuels__esrp') }} as entree_fpt_contractuels__esrp,
        {{ clean_integer('entree_fpt_contractuels__ueros') }} as entree_fpt_contractuels__ueros,
        {{ clean_integer('entree_jamais_travaille__deac') }} as entree_jamais_travaille__deac,
        {{ clean_integer('entree_jamais_travaille__espo') }} as entree_jamais_travaille__espo,
        {{ clean_integer('entree_jamais_travaille__esrp') }} as entree_jamais_travaille__esrp,
        {{ clean_integer('entree_jamais_travaille__ueros') }} as entree_jamais_travaille__ueros,
        {{ clean_integer('entree_non_salarie__deac') }} as entree_non_salarie__deac,
        {{ clean_integer('entree_non_salarie__espo') }} as entree_non_salarie__espo,
        {{ clean_integer('entree_non_salarie__esrp') }} as entree_non_salarie__esrp,
        {{ clean_integer('entree_non_salarie__ueros') }} as entree_non_salarie__ueros,
        {{ clean_integer('entree_sans_emploi_1_2ans__deac') }} as entree_sans_emploi_1_2ans__deac,
        {{ clean_integer('entree_sans_emploi_1_2ans__espo') }} as entree_sans_emploi_1_2ans__espo,
        {{ clean_integer('entree_sans_emploi_1_2ans__esrp') }} as entree_sans_emploi_1_2ans__esrp,
        {{ clean_integer('entree_sans_emploi_1_2ans__ueros') }} as entree_sans_emploi_1_2ans__ueros,
        {{ clean_integer('entree_sans_emploi__deac') }} as entree_sans_emploi__deac,
        {{ clean_integer('entree_sans_emploi__espo') }} as entree_sans_emploi__espo,
        {{ clean_integer('entree_sans_emploi__esrp') }} as entree_sans_emploi__esrp,
        {{ clean_integer('entree_sans_emploi__ueros') }} as entree_sans_emploi__ueros,
        {{ clean_integer('entree_sans_emploi_moins1an__deac') }} as entree_sans_emploi_moins1an__deac,
        {{ clean_integer('entree_sans_emploi_moins1an__espo') }} as entree_sans_emploi_moins1an__espo,
        {{ clean_integer('entree_sans_emploi_moins1an__esrp') }} as entree_sans_emploi_moins1an__esrp,
        {{ clean_integer('entree_sans_emploi_moins1an__ueros') }} as entree_sans_emploi_moins1an__ueros,
        {{ clean_integer('entree_sans_emploi_plus2ans__deac') }} as entree_sans_emploi_plus2ans__deac,
        {{ clean_integer('entree_sans_emploi_plus2ans__espo') }} as entree_sans_emploi_plus2ans__espo,
        {{ clean_integer('entree_sans_emploi_plus2ans__esrp') }} as entree_sans_emploi_plus2ans__esrp,
        {{ clean_integer('entree_sans_emploi_plus2ans__ueros') }} as entree_sans_emploi_plus2ans__ueros,
        {{ clean_text('es_departement') }} as es_departement,
        {{ clean_text('es_nom') }} as es_nom,
        {{ clean_text('finess_json') }} as finess_json,
        {{ clean_text('finess_main') }} as finess_main,
        {{ clean_integer('formation_niveau2__deac') }} as formation_niveau2__deac,
        {{ clean_integer('formation_niveau2__espo') }} as formation_niveau2__espo,
        {{ clean_integer('formation_niveau2__esrp') }} as formation_niveau2__esrp,
        {{ clean_integer('formation_niveau2__ueros') }} as formation_niveau2__ueros,
        {{ clean_integer('formation_niveau3__deac') }} as formation_niveau3__deac,
        {{ clean_integer('formation_niveau3__espo') }} as formation_niveau3__espo,
        {{ clean_integer('formation_niveau3__esrp') }} as formation_niveau3__esrp,
        {{ clean_integer('formation_niveau3__ueros') }} as formation_niveau3__ueros,
        {{ clean_integer('formation_niveau4__deac') }} as formation_niveau4__deac,
        {{ clean_integer('formation_niveau4__espo') }} as formation_niveau4__espo,
        {{ clean_integer('formation_niveau4__esrp') }} as formation_niveau4__esrp,
        {{ clean_integer('formation_niveau4__ueros') }} as formation_niveau4__ueros,
        {{ clean_integer('formation_niveau5__deac') }} as formation_niveau5__deac,
        {{ clean_integer('formation_niveau5__espo') }} as formation_niveau5__espo,
        {{ clean_integer('formation_niveau5__esrp') }} as formation_niveau5__esrp,
        {{ clean_integer('formation_niveau5__ueros') }} as formation_niveau5__ueros,
        {{ clean_integer('formation_niveau6__deac') }} as formation_niveau6__deac,
        {{ clean_integer('formation_niveau6__espo') }} as formation_niveau6__espo,
        {{ clean_integer('formation_niveau6__esrp') }} as formation_niveau6__esrp,
        {{ clean_integer('formation_niveau6__ueros') }} as formation_niveau6__ueros,
        {{ clean_integer('formation_niveau7__deac') }} as formation_niveau7__deac,
        {{ clean_integer('formation_niveau7__espo') }} as formation_niveau7__espo,
        {{ clean_integer('formation_niveau7__esrp') }} as formation_niveau7__esrp,
        {{ clean_integer('formation_niveau7__ueros') }} as formation_niveau7__ueros,
        {{ clean_integer('genre_femmes__deac') }} as genre_femmes__deac,
        {{ clean_integer('genre_femmes__espo') }} as genre_femmes__espo,
        {{ clean_integer('genre_femmes__esrp') }} as genre_femmes__esrp,
        {{ clean_integer('genre_femmes__ueros') }} as genre_femmes__ueros,
        {{ clean_integer('genre_hommes__deac') }} as genre_hommes__deac,
        {{ clean_integer('genre_hommes__espo') }} as genre_hommes__espo,
        {{ clean_integer('genre_hommes__esrp') }} as genre_hommes__esrp,
        {{ clean_integer('genre_hommes__ueros') }} as genre_hommes__ueros,
        {{ clean_integer('genre_nonbinaires__deac') }} as genre_nonbinaires__deac,
        {{ clean_integer('genre_nonbinaires__espo') }} as genre_nonbinaires__espo,
        {{ clean_integer('genre_nonbinaires__esrp') }} as genre_nonbinaires__esrp,
        {{ clean_integer('genre_nonbinaires__ueros') }} as genre_nonbinaires__ueros,
        {{ clean_integer('handicap_auditives_a__deac') }} as handicap_auditives_a__deac,
        {{ clean_integer('handicap_auditives_a__espo') }} as handicap_auditives_a__espo,
        {{ clean_integer('handicap_auditives_a__esrp') }} as handicap_auditives_a__esrp,
        {{ clean_integer('handicap_auditives_a__ueros') }} as handicap_auditives_a__ueros,
        {{ clean_integer('handicap_auditives_p__deac') }} as handicap_auditives_p__deac,
        {{ clean_integer('handicap_auditives_p__espo') }} as handicap_auditives_p__espo,
        {{ clean_integer('handicap_auditives_p__esrp') }} as handicap_auditives_p__esrp,
        {{ clean_integer('handicap_auditives_p__ueros') }} as handicap_auditives_p__ueros,
        {{ clean_integer('handicap_autisme_a__deac') }} as handicap_autisme_a__deac,
        {{ clean_integer('handicap_autisme_a__espo') }} as handicap_autisme_a__espo,
        {{ clean_integer('handicap_autisme_a__esrp') }} as handicap_autisme_a__esrp,
        {{ clean_integer('handicap_autisme_a__ueros') }} as handicap_autisme_a__ueros,
        {{ clean_integer('handicap_autisme_p__deac') }} as handicap_autisme_p__deac,
        {{ clean_integer('handicap_autisme_p__espo') }} as handicap_autisme_p__espo,
        {{ clean_integer('handicap_autisme_p__esrp') }} as handicap_autisme_p__esrp,
        {{ clean_integer('handicap_autisme_p__ueros') }} as handicap_autisme_p__ueros,
        {{ clean_integer('handicap_autres_a__deac') }} as handicap_autres_a__deac,
        {{ clean_integer('handicap_autres_a__espo') }} as handicap_autres_a__espo,
        {{ clean_integer('handicap_autres_a__esrp') }} as handicap_autres_a__esrp,
        {{ clean_integer('handicap_autres_a__ueros') }} as handicap_autres_a__ueros,
        {{ clean_integer('handicap_autres_p__deac') }} as handicap_autres_p__deac,
        {{ clean_integer('handicap_autres_p__espo') }} as handicap_autres_p__espo,
        {{ clean_integer('handicap_autres_p__esrp') }} as handicap_autres_p__esrp,
        {{ clean_integer('handicap_autres_p__ueros') }} as handicap_autres_p__ueros,
        {{ clean_integer('handicap_cerebrolesions_a__deac') }} as handicap_cerebrolesions_a__deac,
        {{ clean_integer('handicap_cerebrolesions_a__espo') }} as handicap_cerebrolesions_a__espo,
        {{ clean_integer('handicap_cerebrolesions_a__esrp') }} as handicap_cerebrolesions_a__esrp,
        {{ clean_integer('handicap_cerebrolesions_a__ueros') }} as handicap_cerebrolesions_a__ueros,
        {{ clean_integer('handicap_cerebrolesions_p__deac') }} as handicap_cerebrolesions_p__deac,
        {{ clean_integer('handicap_cerebrolesions_p__espo') }} as handicap_cerebrolesions_p__espo,
        {{ clean_integer('handicap_cerebrolesions_p__esrp') }} as handicap_cerebrolesions_p__esrp,
        {{ clean_integer('handicap_cerebrolesions_p__ueros') }} as handicap_cerebrolesions_p__ueros,
        {{ clean_integer('handicap_diagnostics_a__deac') }} as handicap_diagnostics_a__deac,
        {{ clean_integer('handicap_diagnostics_a__espo') }} as handicap_diagnostics_a__espo,
        {{ clean_integer('handicap_diagnostics_a__esrp') }} as handicap_diagnostics_a__esrp,
        {{ clean_integer('handicap_diagnostics_a__ueros') }} as handicap_diagnostics_a__ueros,
        {{ clean_integer('handicap_diagnostics_p__deac') }} as handicap_diagnostics_p__deac,
        {{ clean_integer('handicap_diagnostics_p__espo') }} as handicap_diagnostics_p__espo,
        {{ clean_integer('handicap_diagnostics_p__esrp') }} as handicap_diagnostics_p__esrp,
        {{ clean_integer('handicap_diagnostics_p__ueros') }} as handicap_diagnostics_p__ueros,
        {{ clean_integer('handicap_intellectuelles_a__deac') }} as handicap_intellectuelles_a__deac,
        {{ clean_integer('handicap_intellectuelles_a__espo') }} as handicap_intellectuelles_a__espo,
        {{ clean_integer('handicap_intellectuelles_a__esrp') }} as handicap_intellectuelles_a__esrp,
        {{ clean_integer('handicap_intellectuelles_a__ueros') }} as handicap_intellectuelles_a__ueros,
        {{ clean_integer('handicap_intellectuelles_p__deac') }} as handicap_intellectuelles_p__deac,
        {{ clean_integer('handicap_intellectuelles_p__espo') }} as handicap_intellectuelles_p__espo,
        {{ clean_integer('handicap_intellectuelles_p__esrp') }} as handicap_intellectuelles_p__esrp,
        {{ clean_integer('handicap_intellectuelles_p__ueros') }} as handicap_intellectuelles_p__ueros,
        {{ clean_integer('handicap_langage_a__deac') }} as handicap_langage_a__deac,
        {{ clean_integer('handicap_langage_a__espo') }} as handicap_langage_a__espo,
        {{ clean_integer('handicap_langage_a__esrp') }} as handicap_langage_a__esrp,
        {{ clean_integer('handicap_langage_a__ueros') }} as handicap_langage_a__ueros,
        {{ clean_integer('handicap_langage_p__deac') }} as handicap_langage_p__deac,
        {{ clean_integer('handicap_langage_p__espo') }} as handicap_langage_p__espo,
        {{ clean_integer('handicap_langage_p__esrp') }} as handicap_langage_p__esrp,
        {{ clean_integer('handicap_langage_p__ueros') }} as handicap_langage_p__ueros,
        {{ clean_integer('handicap_metaboliques_a__deac') }} as handicap_metaboliques_a__deac,
        {{ clean_integer('handicap_metaboliques_a__espo') }} as handicap_metaboliques_a__espo,
        {{ clean_integer('handicap_metaboliques_a__esrp') }} as handicap_metaboliques_a__esrp,
        {{ clean_integer('handicap_metaboliques_a__ueros') }} as handicap_metaboliques_a__ueros,
        {{ clean_integer('handicap_metaboliques_p__deac') }} as handicap_metaboliques_p__deac,
        {{ clean_integer('handicap_metaboliques_p__espo') }} as handicap_metaboliques_p__espo,
        {{ clean_integer('handicap_metaboliques_p__esrp') }} as handicap_metaboliques_p__esrp,
        {{ clean_integer('handicap_metaboliques_p__ueros') }} as handicap_metaboliques_p__ueros,
        {{ clean_integer('handicap_motrices_a__deac') }} as handicap_motrices_a__deac,
        {{ clean_integer('handicap_motrices_a__espo') }} as handicap_motrices_a__espo,
        {{ clean_integer('handicap_motrices_a__esrp') }} as handicap_motrices_a__esrp,
        {{ clean_integer('handicap_motrices_a__ueros') }} as handicap_motrices_a__ueros,
        {{ clean_integer('handicap_motrices_p__deac') }} as handicap_motrices_p__deac,
        {{ clean_integer('handicap_motrices_p__espo') }} as handicap_motrices_p__espo,
        {{ clean_integer('handicap_motrices_p__esrp') }} as handicap_motrices_p__esrp,
        {{ clean_integer('handicap_motrices_p__ueros') }} as handicap_motrices_p__ueros,
        {{ clean_integer('handicap_polyhandicap_a__deac') }} as handicap_polyhandicap_a__deac,
        {{ clean_integer('handicap_polyhandicap_a__espo') }} as handicap_polyhandicap_a__espo,
        {{ clean_integer('handicap_polyhandicap_a__esrp') }} as handicap_polyhandicap_a__esrp,
        {{ clean_integer('handicap_polyhandicap_a__ueros') }} as handicap_polyhandicap_a__ueros,
        {{ clean_integer('handicap_polyhandicap_p__deac') }} as handicap_polyhandicap_p__deac,
        {{ clean_integer('handicap_polyhandicap_p__espo') }} as handicap_polyhandicap_p__espo,
        {{ clean_integer('handicap_polyhandicap_p__esrp') }} as handicap_polyhandicap_p__esrp,
        {{ clean_integer('handicap_polyhandicap_p__ueros') }} as handicap_polyhandicap_p__ueros,
        {{ clean_integer('handicap_psychiques_a__deac') }} as handicap_psychiques_a__deac,
        {{ clean_integer('handicap_psychiques_a__espo') }} as handicap_psychiques_a__espo,
        {{ clean_integer('handicap_psychiques_a__esrp') }} as handicap_psychiques_a__esrp,
        {{ clean_integer('handicap_psychiques_a__ueros') }} as handicap_psychiques_a__ueros,
        {{ clean_integer('handicap_psychiques_p__deac') }} as handicap_psychiques_p__deac,
        {{ clean_integer('handicap_psychiques_p__espo') }} as handicap_psychiques_p__espo,
        {{ clean_integer('handicap_psychiques_p__esrp') }} as handicap_psychiques_p__esrp,
        {{ clean_integer('handicap_psychiques_p__ueros') }} as handicap_psychiques_p__ueros,
        {{ clean_integer('handicap_tcc_a__deac') }} as handicap_tcc_a__deac,
        {{ clean_integer('handicap_tcc_a__espo') }} as handicap_tcc_a__espo,
        {{ clean_integer('handicap_tcc_a__esrp') }} as handicap_tcc_a__esrp,
        {{ clean_integer('handicap_tcc_a__ueros') }} as handicap_tcc_a__ueros,
        {{ clean_integer('handicap_tcc_p__deac') }} as handicap_tcc_p__deac,
        {{ clean_integer('handicap_tcc_p__espo') }} as handicap_tcc_p__espo,
        {{ clean_integer('handicap_tcc_p__esrp') }} as handicap_tcc_p__esrp,
        {{ clean_integer('handicap_tcc_p__ueros') }} as handicap_tcc_p__ueros,
        {{ clean_integer('handicap_visuelles_a__deac') }} as handicap_visuelles_a__deac,
        {{ clean_integer('handicap_visuelles_a__espo') }} as handicap_visuelles_a__espo,
        {{ clean_integer('handicap_visuelles_a__esrp') }} as handicap_visuelles_a__esrp,
        {{ clean_integer('handicap_visuelles_a__ueros') }} as handicap_visuelles_a__ueros,
        {{ clean_integer('handicap_visuelles_p__deac') }} as handicap_visuelles_p__deac,
        {{ clean_integer('handicap_visuelles_p__espo') }} as handicap_visuelles_p__espo,
        {{ clean_integer('handicap_visuelles_p__esrp') }} as handicap_visuelles_p__esrp,
        {{ clean_integer('handicap_visuelles_p__ueros') }} as handicap_visuelles_p__ueros,
        {{ clean_integer('lesion_autres__deac') }} as lesion_autres__deac,
        {{ clean_integer('lesion_autres__espo') }} as lesion_autres__espo,
        {{ clean_integer('lesion_autres__esrp') }} as lesion_autres__esrp,
        {{ clean_integer('lesion_autres__ueros') }} as lesion_autres__ueros,
        {{ clean_integer('lesion_avc__deac') }} as lesion_avc__deac,
        {{ clean_integer('lesion_avc__espo') }} as lesion_avc__espo,
        {{ clean_integer('lesion_avc__esrp') }} as lesion_avc__esrp,
        {{ clean_integer('lesion_avc__ueros') }} as lesion_avc__ueros,
        {{ clean_integer('lesion_epilepsie__deac') }} as lesion_epilepsie__deac,
        {{ clean_integer('lesion_epilepsie__espo') }} as lesion_epilepsie__espo,
        {{ clean_integer('lesion_epilepsie__esrp') }} as lesion_epilepsie__esrp,
        {{ clean_integer('lesion_epilepsie__ueros') }} as lesion_epilepsie__ueros,
        {{ clean_integer('lesion_inconnue__deac') }} as lesion_inconnue__deac,
        {{ clean_integer('lesion_inconnue__espo') }} as lesion_inconnue__espo,
        {{ clean_integer('lesion_inconnue__esrp') }} as lesion_inconnue__esrp,
        {{ clean_integer('lesion_inconnue__ueros') }} as lesion_inconnue__ueros,
        {{ clean_integer('lesion_traumatisme__deac') }} as lesion_traumatisme__deac,
        {{ clean_integer('lesion_traumatisme__espo') }} as lesion_traumatisme__espo,
        {{ clean_integer('lesion_traumatisme__esrp') }} as lesion_traumatisme__esrp,
        {{ clean_integer('lesion_traumatisme__ueros') }} as lesion_traumatisme__ueros,
        {{ clean_integer('lesion_tumeur__deac') }} as lesion_tumeur__deac,
        {{ clean_integer('lesion_tumeur__espo') }} as lesion_tumeur__espo,
        {{ clean_integer('lesion_tumeur__esrp') }} as lesion_tumeur__esrp,
        {{ clean_integer('lesion_tumeur__ueros') }} as lesion_tumeur__ueros,
        {{ clean_integer('origine_accident_travail__deac') }} as origine_accident_travail__deac,
        {{ clean_integer('origine_accident_travail__espo') }} as origine_accident_travail__espo,
        {{ clean_integer('origine_accident_travail__esrp') }} as origine_accident_travail__esrp,
        {{ clean_integer('origine_accident_travail__ueros') }} as origine_accident_travail__ueros,
        {{ clean_integer('origine_accident_vie__deac') }} as origine_accident_vie__deac,
        {{ clean_integer('origine_accident_vie__espo') }} as origine_accident_vie__espo,
        {{ clean_integer('origine_accident_vie__esrp') }} as origine_accident_vie__esrp,
        {{ clean_integer('origine_accident_vie__ueros') }} as origine_accident_vie__ueros,
        {{ clean_integer('origine_autres__deac') }} as origine_autres__deac,
        {{ clean_integer('origine_autres__espo') }} as origine_autres__espo,
        {{ clean_integer('origine_autres__esrp') }} as origine_autres__esrp,
        {{ clean_integer('origine_autres__ueros') }} as origine_autres__ueros,
        {{ clean_integer('origine_congenitale__deac') }} as origine_congenitale__deac,
        {{ clean_integer('origine_congenitale__espo') }} as origine_congenitale__espo,
        {{ clean_integer('origine_congenitale__esrp') }} as origine_congenitale__esrp,
        {{ clean_integer('origine_congenitale__ueros') }} as origine_congenitale__ueros,
        {{ clean_integer('origine_inconnue__deac') }} as origine_inconnue__deac,
        {{ clean_integer('origine_inconnue__espo') }} as origine_inconnue__espo,
        {{ clean_integer('origine_inconnue__esrp') }} as origine_inconnue__esrp,
        {{ clean_integer('origine_inconnue__ueros') }} as origine_inconnue__ueros,
        {{ clean_integer('origine_maladie__deac') }} as origine_maladie__deac,
        {{ clean_integer('origine_maladie__espo') }} as origine_maladie__espo,
        {{ clean_integer('origine_maladie__esrp') }} as origine_maladie__esrp,
        {{ clean_integer('origine_maladie__ueros') }} as origine_maladie__ueros,
        {{ clean_integer('origine_maladie_pro__deac') }} as origine_maladie_pro__deac,
        {{ clean_integer('origine_maladie_pro__espo') }} as origine_maladie_pro__espo,
        {{ clean_integer('origine_maladie_pro__esrp') }} as origine_maladie_pro__esrp,
        {{ clean_integer('origine_maladie_pro__ueros') }} as origine_maladie_pro__ueros,
        {{ clean_text('orp_autre_eval') }} as orp_autre_eval,
        {{ clean_text('orp_autre_eval_precision') }} as orp_autre_eval_precision,
        {{ clean_text('orp_autre_parcours') }} as orp_autre_parcours,
        {{ clean_text('orp_autre_parcours_precision') }} as orp_autre_parcours_precision,
        {{ clean_text('orp_formation_accomp_certif') }} as orp_formation_accomp_certif,
        {{ clean_text('orp_formation_accomp_pro') }} as orp_formation_accomp_pro,
        {{ clean_text('orp_formation_certif') }} as orp_formation_certif,
        {{ clean_text('orp_formation_pro') }} as orp_formation_pro,
        {{ clean_text('orp_orientation_espo') }} as orp_orientation_espo,
        {{ clean_text('orp_parcours_qualif') }} as orp_parcours_qualif,
        {{ clean_text('orp_parcours_sociopro') }} as orp_parcours_sociopro,
        {{ clean_text('orp_pec') }} as orp_pec,
        {{ clean_text('orp_remise_niveau') }} as orp_remise_niveau,
        {{ clean_integer('pathologies_1__deac') }} as pathologies_1__deac,
        {{ clean_integer('pathologies_1__espo') }} as pathologies_1__espo,
        {{ clean_integer('pathologies_1__esrp') }} as pathologies_1__esrp,
        {{ clean_integer('pathologies_1__ueros') }} as pathologies_1__ueros,
        {{ clean_integer('pathologies_2__deac') }} as pathologies_2__deac,
        {{ clean_integer('pathologies_2__espo') }} as pathologies_2__espo,
        {{ clean_integer('pathologies_2__esrp') }} as pathologies_2__esrp,
        {{ clean_integer('pathologies_2__ueros') }} as pathologies_2__ueros,
        {{ clean_integer('pathologies_3plus__deac') }} as pathologies_3plus__deac,
        {{ clean_integer('pathologies_3plus__espo') }} as pathologies_3plus__espo,
        {{ clean_integer('pathologies_3plus__esrp') }} as pathologies_3plus__esrp,
        {{ clean_integer('pathologies_3plus__ueros') }} as pathologies_3plus__ueros,
        {{ clean_integer('pathologies_inconnu__deac') }} as pathologies_inconnu__deac,
        {{ clean_integer('pathologies_inconnu__espo') }} as pathologies_inconnu__espo,
        {{ clean_integer('pathologies_inconnu__esrp') }} as pathologies_inconnu__esrp,
        {{ clean_integer('pathologies_inconnu__ueros') }} as pathologies_inconnu__ueros,
        {{ clean_text('prestations_details_json') }} as prestations_details_json,
        {{ clean_text('prestations_orp_json') }} as prestations_orp_json,
        {{ clean_text('q34_alternatif') }} as q34_alternatif,
        {{ clean_boolean('q35_alternatives') }} as q35_alternatives,
        {{ clean_boolean('q35_comptabilite_we') }} as q35_comptabilite_we,
        {{ clean_boolean('q35_fermetures') }} as q35_fermetures,
        {{ clean_integer('q35_fermetures_semaines') }} as q35_fermetures_semaines,
        {{ clean_boolean('q36_externe') }} as q36_externe,
        {{ clean_text('q36_participation') }} as q36_participation,
        {{ clean_boolean('q36_weekend') }} as q36_weekend,
        {{ clean_boolean('q37_weekend') }} as q37_weekend,
        {{ clean_text('q52_autre') }} as q52_autre,
        {{ clean_text('q52_autre_precision') }} as q52_autre_precision,
        {{ clean_integer('q53_accompagnes__deac') }} as q53_accompagnes__deac,
        {{ clean_integer('q53_accompagnes__espo') }} as q53_accompagnes__espo,
        {{ clean_integer('q53_accompagnes__esrp') }} as q53_accompagnes__esrp,
        {{ clean_integer('q53_accompagnes__ueros') }} as q53_accompagnes__ueros,
        {{ clean_boolean('q53_afpa') }} as q53_afpa,
        {{ clean_integer('q54_sorties__deac') }} as q54_sorties__deac,
        {{ clean_integer('q54_sorties__espo') }} as q54_sorties__espo,
        {{ clean_integer('q54_sorties__esrp') }} as q54_sorties__esrp,
        {{ clean_integer('q54_sorties__ueros') }} as q54_sorties__ueros,
        {{ clean_text('q55_journees') }} as q55_journees,
        {{ clean_integer('q55_journees__deac') }} as q55_journees__deac,
        {{ clean_integer('q55_journees__espo') }} as q55_journees__espo,
        {{ clean_integer('q55_journees__esrp') }} as q55_journees__esrp,
        {{ clean_integer('q55_journees__ueros') }} as q55_journees__ueros,
        {{ clean_integer('ressources_aah__deac') }} as ressources_aah__deac,
        {{ clean_integer('ressources_aah__espo') }} as ressources_aah__espo,
        {{ clean_integer('ressources_aah__esrp') }} as ressources_aah__esrp,
        {{ clean_integer('ressources_aah__ueros') }} as ressources_aah__ueros,
        {{ clean_integer('ressources_aucune__deac') }} as ressources_aucune__deac,
        {{ clean_integer('ressources_aucune__espo') }} as ressources_aucune__espo,
        {{ clean_integer('ressources_aucune__esrp') }} as ressources_aucune__esrp,
        {{ clean_integer('ressources_aucune__ueros') }} as ressources_aucune__ueros,
        {{ clean_integer('ressources_autres__deac') }} as ressources_autres__deac,
        {{ clean_integer('ressources_autres__espo') }} as ressources_autres__espo,
        {{ clean_integer('ressources_autres__esrp') }} as ressources_autres__esrp,
        {{ clean_integer('ressources_autres__ueros') }} as ressources_autres__ueros,
        {{ clean_integer('ressources_chomage__deac') }} as ressources_chomage__deac,
        {{ clean_integer('ressources_chomage__espo') }} as ressources_chomage__espo,
        {{ clean_integer('ressources_chomage__esrp') }} as ressources_chomage__esrp,
        {{ clean_integer('ressources_chomage__ueros') }} as ressources_chomage__ueros,
        {{ clean_integer('ressources_ij__deac') }} as ressources_ij__deac,
        {{ clean_integer('ressources_ij__espo') }} as ressources_ij__espo,
        {{ clean_integer('ressources_ij__esrp') }} as ressources_ij__esrp,
        {{ clean_integer('ressources_ij__ueros') }} as ressources_ij__ueros,
        {{ clean_integer('ressources_inconnu__deac') }} as ressources_inconnu__deac,
        {{ clean_integer('ressources_inconnu__espo') }} as ressources_inconnu__espo,
        {{ clean_integer('ressources_inconnu__esrp') }} as ressources_inconnu__esrp,
        {{ clean_integer('ressources_inconnu__ueros') }} as ressources_inconnu__ueros,
        {{ clean_integer('ressources_remuneration__deac') }} as ressources_remuneration__deac,
        {{ clean_integer('ressources_remuneration__espo') }} as ressources_remuneration__espo,
        {{ clean_integer('ressources_remuneration__esrp') }} as ressources_remuneration__esrp,
        {{ clean_integer('ressources_remuneration__ueros') }} as ressources_remuneration__ueros,
        {{ clean_integer('ressources_rentes__deac') }} as ressources_rentes__deac,
        {{ clean_integer('ressources_rentes__espo') }} as ressources_rentes__espo,
        {{ clean_integer('ressources_rentes__esrp') }} as ressources_rentes__esrp,
        {{ clean_integer('ressources_rentes__ueros') }} as ressources_rentes__ueros,
        {{ clean_integer('ressources_rsa__deac') }} as ressources_rsa__deac,
        {{ clean_integer('ressources_rsa__espo') }} as ressources_rsa__espo,
        {{ clean_integer('ressources_rsa__esrp') }} as ressources_rsa__esrp,
        {{ clean_integer('ressources_rsa__ueros') }} as ressources_rsa__ueros,
        {{ clean_boolean('saisie_terminee') }} as saisie_terminee,
        {{ clean_integer('sorties_anticipees__deac') }} as sorties_anticipees__deac,
        {{ clean_integer('sorties_anticipees__espo') }} as sorties_anticipees__espo,
        {{ clean_integer('sorties_anticipees__esrp') }} as sorties_anticipees__esrp,
        {{ clean_integer('sorties_anticipees__ueros') }} as sorties_anticipees__ueros,
        {{ clean_integer('sorties_raison_autres__deac') }} as sorties_raison_autres__deac,
        {{ clean_integer('sorties_raison_autres__espo') }} as sorties_raison_autres__espo,
        {{ clean_integer('sorties_raison_autres__esrp') }} as sorties_raison_autres__esrp,
        {{ clean_integer('sorties_raison_autres__ueros') }} as sorties_raison_autres__ueros,
        {{ clean_integer('sorties_raison_disciplinaire__deac') }} as sorties_raison_disciplinaire__deac,
        {{ clean_integer('sorties_raison_disciplinaire__espo') }} as sorties_raison_disciplinaire__espo,
        {{ clean_integer('sorties_raison_disciplinaire__esrp') }} as sorties_raison_disciplinaire__esrp,
        {{ clean_integer('sorties_raison_disciplinaire__ueros') }} as sorties_raison_disciplinaire__ueros,
        {{ clean_integer('sorties_raison_emploi__deac') }} as sorties_raison_emploi__deac,
        {{ clean_integer('sorties_raison_emploi__espo') }} as sorties_raison_emploi__espo,
        {{ clean_integer('sorties_raison_emploi__esrp') }} as sorties_raison_emploi__esrp,
        {{ clean_integer('sorties_raison_emploi__ueros') }} as sorties_raison_emploi__ueros,
        {{ clean_integer('sorties_raison_inconnue__deac') }} as sorties_raison_inconnue__deac,
        {{ clean_integer('sorties_raison_inconnue__espo') }} as sorties_raison_inconnue__espo,
        {{ clean_integer('sorties_raison_inconnue__esrp') }} as sorties_raison_inconnue__esrp,
        {{ clean_integer('sorties_raison_inconnue__ueros') }} as sorties_raison_inconnue__ueros,
        {{ clean_integer('sorties_raison_objectif__deac') }} as sorties_raison_objectif__deac,
        {{ clean_integer('sorties_raison_objectif__espo') }} as sorties_raison_objectif__espo,
        {{ clean_integer('sorties_raison_objectif__esrp') }} as sorties_raison_objectif__esrp,
        {{ clean_integer('sorties_raison_objectif__ueros') }} as sorties_raison_objectif__ueros,
        {{ clean_integer('sorties_raison_reorientation__deac') }} as sorties_raison_reorientation__deac,
        {{ clean_integer('sorties_raison_reorientation__espo') }} as sorties_raison_reorientation__espo,
        {{ clean_integer('sorties_raison_reorientation__esrp') }} as sorties_raison_reorientation__esrp,
        {{ clean_integer('sorties_raison_reorientation__ueros') }} as sorties_raison_reorientation__ueros,
        {{ clean_integer('sorties_raison_sante__deac') }} as sorties_raison_sante__deac,
        {{ clean_integer('sorties_raison_sante__espo') }} as sorties_raison_sante__espo,
        {{ clean_integer('sorties_raison_sante__esrp') }} as sorties_raison_sante__esrp,
        {{ clean_integer('sorties_raison_sante__ueros') }} as sorties_raison_sante__ueros,
        {{ clean_integer('sorties_raison_volontaire__deac') }} as sorties_raison_volontaire__deac,
        {{ clean_integer('sorties_raison_volontaire__espo') }} as sorties_raison_volontaire__espo,
        {{ clean_integer('sorties_raison_volontaire__esrp') }} as sorties_raison_volontaire__esrp,
        {{ clean_integer('sorties_raison_volontaire__ueros') }} as sorties_raison_volontaire__ueros,
        {{ clean_integer('suspensions_autres__deac') }} as suspensions_autres__deac,
        {{ clean_integer('suspensions_autres__espo') }} as suspensions_autres__espo,
        {{ clean_integer('suspensions_autres__esrp') }} as suspensions_autres__esrp,
        {{ clean_integer('suspensions_autres__ueros') }} as suspensions_autres__ueros,
        {{ clean_integer('suspensions_handicap__deac') }} as suspensions_handicap__deac,
        {{ clean_integer('suspensions_handicap__espo') }} as suspensions_handicap__espo,
        {{ clean_integer('suspensions_handicap__esrp') }} as suspensions_handicap__esrp,
        {{ clean_integer('suspensions_handicap__ueros') }} as suspensions_handicap__ueros,
        {{ clean_integer('suspensions_nb__deac') }} as suspensions_nb__deac,
        {{ clean_integer('suspensions_nb__espo') }} as suspensions_nb__espo,
        {{ clean_integer('suspensions_nb__esrp') }} as suspensions_nb__esrp,
        {{ clean_integer('suspensions_nb__ueros') }} as suspensions_nb__ueros,
        {{ clean_integer('suspensions_parcours__deac') }} as suspensions_parcours__deac,
        {{ clean_integer('suspensions_parcours__espo') }} as suspensions_parcours__espo,
        {{ clean_integer('suspensions_parcours__esrp') }} as suspensions_parcours__esrp,
        {{ clean_integer('suspensions_parcours__ueros') }} as suspensions_parcours__ueros,
        {{ clean_integer('suspensions_reprises__deac') }} as suspensions_reprises__deac,
        {{ clean_integer('suspensions_reprises__espo') }} as suspensions_reprises__espo,
        {{ clean_integer('suspensions_reprises__esrp') }} as suspensions_reprises__esrp,
        {{ clean_integer('suspensions_reprises__ueros') }} as suspensions_reprises__ueros,
        {{ clean_integer('suspensions_sante__deac') }} as suspensions_sante__deac,
        {{ clean_integer('suspensions_sante__espo') }} as suspensions_sante__espo,
        {{ clean_integer('suspensions_sante__esrp') }} as suspensions_sante__esrp,
        {{ clean_integer('suspensions_sante__ueros') }} as suspensions_sante__ueros,
        {{ clean_integer('suspensions_sociale__deac') }} as suspensions_sociale__deac,
        {{ clean_integer('suspensions_sociale__espo') }} as suspensions_sociale__espo,
        {{ clean_integer('suspensions_sociale__esrp') }} as suspensions_sociale__esrp,
        {{ clean_integer('suspensions_sociale__ueros') }} as suspensions_sociale__ueros,
        {{ clean_text('validateur_email') }} as validateur_email,
        {{ clean_text('validateur_nom') }} as validateur_nom,
        {{ clean_text('validateur_prenom') }} as validateur_prenom,
        {{ clean_boolean('pec_avec_orp_cdaph') }} as pec_avec_orp_cdaph,
        {{ clean_boolean('pec_sans_orp_cdaph') }} as pec_sans_orp_cdaph,
        {{ clean_boolean('autre_dispositif_eval') }} as autre_dispositif_eval,
        {{ clean_text('autre_dispositif_eval_avec_orp_cdaph') }} as autre_dispositif_eval_avec_orp_cdaph,
        {{ clean_boolean('autre_dispositif_eval_sans_orp_cdaph') }} as autre_dispositif_eval_sans_orp_cdaph,
        {{ clean_text('orp_autre_dispositif_eval') }} as orp_autre_dispositif_eval,
        {{ clean_text('catalogue_formations_json') }} as catalogue_formations_json,
        {{ clean_text('emploi_indicateurs_json') }} as emploi_indicateurs_json,
        {{ clean_text('prestations_indirectes_json') }} as prestations_indirectes_json,
        {{ clean_boolean('q38_dui') }} as q38_dui,
        {{ clean_text('q38_dui_lequel') }} as q38_dui_lequel,
        {{ clean_boolean('q38_autre_outil_informatise') }} as q38_autre_outil_informatise,
        {{ clean_text('q38_outil_suivi_actuel') }} as q38_outil_suivi_actuel

    from source

)

select *
from renamed
