name: Git Checks

on: [pull_request]

jobs:
  block-fixup:
    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - name: Block Fixup Commit Merge
      uses: 13rac1/block-fixup-merge-action@bd5504fb9ca0253e109d98eb86b7debc01970cdc # v2.0.0
