name: Label Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  merge_group:

jobs:
  require-label:
    runs-on: ubuntu-latest
    steps:
      - name: Verify changelog label
        uses: mheap/github-action-required-labels@5.5.0
        with:
          mode: exactly
          count: 1
          labels: "changelog:.*|dependencies"
          use_regex: true
      - name: Verify datasource label
        uses: mheap/github-action-required-labels@5.5.0
        with:
          mode: exactly
          count: 1
          labels: "datasource:.*"
          use_regex: true
